services:
  naturedex-db:
    image: mysql:8
    container_name: naturedex-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: naturedex
      MYSQL_USER: natureuser
      MYSQL_PASSWORD: naturepass
    ports:
      - "3306:3306"
    networks:
      - naturedex-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    networks:
      - naturedex-net

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8082:8082"
    networks:
      - naturedex-net

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - user-service
    networks:
      - naturedex-net

  observation-service:
    build: ./observation-service
    container_name: observation-service
    ports:
      - "8083:8083"
    networks:
      - naturedex-net

  species-service:
    build: ./species-service
    container_name: species-service
    ports:
      - "8084:8084"
    networks:
      - naturedex-net

networks:
  naturedex-net:
    driver: bridge
