server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/naturedex_user_service_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: user-service

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: naturedex_super_secure_jwt_secret_2025!
